# Generated by Django 4.2 on 2023-04-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('operation_year', models.IntegerField()),
                ('nb_pos_detected', models.IntegerField()),
                ('surv', models.IntegerField()),
            ],
        ),
    ]
